name: "Build with Jib and publish to DockerHub"
description: "Push builted artifacts to DockerHub"
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  directory:
    description: "Directory"
    required: true
  github_workspace:
    description: "Github workspace"
    required: true  
  github_token:
    description: "Github Token"
    required: true  
runs:
  using: "composite"
  steps:
    - name: Trimm SHA
      uses: drdeath2609/sha-trim-action@v1.1.1
      with:
        sha-length: 7
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
        cache: 'maven'
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
    - name: Release
      shell: bash
      run: mvn compile jib:build -s .mvn/settings.xml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} 
